// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://neaegcjppvnvbghgervx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5lYWVnY2pwcHZudmJnaGdlcnZ4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc5NTA1MTMsImV4cCI6MjA3MzUyNjUxM30.whiIyOkpjEiAgLUjhhVxRI62yX2FXEhWVtveQRNpro4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});